-- 1. Create Configuration Table (Stores the JSON Layout)
create table if not exists app_config (
  id int primary key,
  layout jsonb default '[]'::jsonb,
  updated_at timestamptz default now()
);

-- 2. Create Support Messages Table (For Live Chat)
create table if not exists support_messages (
  id bigint generated by default as identity primary key,
  user_id text,
  content text,
  is_admin boolean default false,
  created_at timestamptz default now()
);

-- 3. Enable Realtime for Chat
alter publication supabase_realtime add table support_messages;
alter publication supabase_realtime add table app_config;

-- 4. Seed Initial Layout (Example SDUI JSON)
insert into app_config (id, layout)
values (1, '[
  {"type": "text", "text": "Secret Console", "style": "h1"},
  {"type": "text", "text": "Live Support & Media Control", "style": "body"},
  {"type": "chat", "title": "Admin Chat", "height": 400}
]')
on conflict (id) do update 
set layout = excluded.layout;
