export const ENV = {
  API_BASE_URL: '',
  API_AUTH_CODE: '',
  IMAGE_BASE_URL: 'https://image.tmdb.org/t/p/w500/',
  BACKEND_URL: '',
  MOVIE_API_KEY: '',
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  APK_VERIFY_SECRET: '',
  PLAYBACK_DEFAULT_REFERER: '',
  PLAYBACK_DEFAULT_USER_AGENT: '',
  PLAYBACK_X_REQUEST_X: '',
  PLAYBACK_ACCEPT_ENCODING: '',
};